config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  resources :links, only: [:create, :show]

  get '/:slug', to: 'links#go', as: :go
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord

  validates :og_url, presence: true
  validates :og_url, format: URI::DEFAULT_PARSER.make_regexp(%w[http https])
  validates :slug, uniqueness: true
  validates_format_of :slug, with: /\A\w+\z/

  before_validation :check_slug

  def check_slug
    if slug.empty? || slug.nil?
      alphabet = ('a'..'z').to_a
      numbers = (0..1).to_a
      options = alphabet + numbers
      self.slug = [0, 0, 0, 0, 0].map { |_n| options.sample }.join
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/links_controller.rb
class LinksController < ApplicationController

  def create
    @link = Link.new(link_params)
    if @link.save
      redirect_to link_path(@link)
    else
      render 'pages/home'
    end
  end

  def show
    @link = Link.find(params[:id])
  end

  def go
    @link = Link.find_by(slug: params[:slug])
    if @link
      redirect_to @link.og_url
    else
      redirect_to root_path
    end
  end

  private

  def link_params
    params.require(:link).permit(:og_url, :slug)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @link = Link.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TSUS - The Simple URL Shortener</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/show.html.erb
<div class="row justify-content-center vw-100">
  <div class="border bg-white vh-50 w-50 my-5 rounded p-4">
    <h2>Your link is:</h2>
    <p> <%= link_to go_url(@link.slug), go_url(@link.slug), target: :_blank %> </p>
    <%= link_to 'Back', root_path %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="row justify-content-center vw-100">
  <h1 class="text-center my-5">The Simple Url Shortener</h1>
  <div class="border bg-white vh-50 w-50 my-3 rounded p-4">
    <%= simple_form_for @link do |f| %>
      <%= f.input :og_url, input_html: { class: "mb-2" }, label: 'Original Url' %>
      <%= f.input :slug, input_html: { class: "mb-2" }, label: 'Slug ( optional )' %>
      <%= f.submit class: 'btn btn-dark  ' %>
    <% end %>
  </div>
</div>